import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { ApiClient } from '@konekte/api-client';
import { messages } from '@konekte/ui';
import type { Locale } from '@konekte/shared-types';
import './styles.css';
const api = new ApiClient(import.meta.env.VITE_API_URL ?? 'http://localhost:4000');
const queryClient = new QueryClient();
function App() {
  const [locale, setLocale] = useState<Locale>('en');
  const [section, setSection] = useState('Dashboard');
  const t = messages[locale];
  const plans = useQuery({ queryKey: ['plans'], queryFn: () => api.plans() });
  const health = useQuery({ queryKey: ['health'], queryFn: () => api.health(), retry: false, refetchInterval: 30_000 });
  const operations = useQuery({ queryKey: ['provider-operations'], queryFn: async () => { const response = await fetch(`${import.meta.env.VITE_API_URL ?? 'http://localhost:4000'}/api/v1/admin/provider-operations`); if (!response.ok) throw new Error('Unavailable'); return response.json() as Promise<Array<{id:string;operationType:string;entityType:string;entityId:string;status:string;attempts:number;safeErrorCode:string|null;updatedAt:string}>>; }, retry: false });
  const providerSummary = useQuery({ queryKey: ['provider-summary'], queryFn: async () => { const response = await fetch(`${import.meta.env.VITE_API_URL ?? 'http://localhost:4000'}/api/v1/admin/provider-operations/summary`); if (!response.ok) throw new Error('Unavailable'); return response.json() as Promise<{provider:{displayName:string;simulated:boolean;healthStatus:string}|null;pendingOperations:number;failedOperations:number;openReconciliationIssues:number}>; }, retry: false });
  const reconciliationIssues = useQuery({ queryKey: ['provider-reconciliation'], queryFn: async () => { const response = await fetch(`${import.meta.env.VITE_API_URL ?? 'http://localhost:4000'}/api/v1/admin/reconciliation-issues`); if (!response.ok) throw new Error('Unavailable'); return response.json() as Promise<Array<{id:string;kind:string;entityType:string;entityId:string;safeDetails:string;detectedAt:string}>>; }, retry: false });
  const providerReadiness = useQuery({ queryKey: ['provider-readiness'], queryFn: async () => { const response = await fetch(`${import.meta.env.VITE_API_URL ?? 'http://localhost:4000'}/api/v1/admin/providers`); if (!response.ok) throw new Error('Unavailable'); return response.json() as Promise<Array<Record<string, unknown>>>; }, retry: false });
  const providerProducts = useQuery({ queryKey: ['provider-products'], queryFn: async () => { const response = await fetch(`${import.meta.env.VITE_API_URL ?? 'http://localhost:4000'}/api/v1/admin/provider-products`); if (!response.ok) throw new Error('Unavailable'); return response.json() as Promise<Array<Record<string, unknown>>>; }, retry: false });
  const planMappings = useQuery({ queryKey: ['plan-mappings'], queryFn: async () => { const response = await fetch(`${import.meta.env.VITE_API_URL ?? 'http://localhost:4000'}/api/v1/admin/plan-mappings`); if (!response.ok) throw new Error('Unavailable'); return response.json() as Promise<Array<Record<string, unknown>>>; }, retry: false });
  const providerCoverage = useQuery({ queryKey: ['provider-coverage', providerReadiness.data?.[0]?.id], enabled: !!providerReadiness.data?.[0]?.id, queryFn: async () => { const id = String(providerReadiness.data?.[0]?.id); const response = await fetch(`${import.meta.env.VITE_API_URL ?? 'http://localhost:4000'}/api/v1/admin/providers/${encodeURIComponent(id)}/coverage/HT`); if (!response.ok) throw new Error('Unavailable'); return response.json() as Promise<Record<string, unknown>>; }, retry: false });
  const sections = ['Dashboard', 'Customers', 'Subscriptions', 'eSIMs', 'Plans', 'Providers', 'Provider Products', 'Plan Mappings', 'Coverage', 'Provider Operations', 'Reconciliation', 'Payments', 'Usage'];
  if (window.location.pathname === '/checkout-return') return <main><div className="brand">konekte.</div><section><h1>{t.payment}</h1><p>{t.paymentPending}</p><p>{t.demo}</p></section></main>;
  return <main><header><div><div className="brand">konekte.</div><span className="eyebrow">DEVELOPMENT / 0.1</span></div><select aria-label="Language" value={locale} onChange={e => setLocale(e.target.value as Locale)}><option value="en">English</option><option value="ht">Kreyòl</option><option value="fr">Français</option></select></header>
    <div className="notice">{t.demo} This console is read-only and uses simulated provider data.</div><div className="heading"><div><h1>{section}</h1><p>{t.adminDetail}</p></div><span className={`status ${health.data ? 'ready' : ''}`}>{health.isPending ? t.loading : health.data ? t.ready : t.unavailable}</span></div>
    <nav className="admin-nav" aria-label="Admin sections">{sections.map(item => <button key={item} className={section === item ? 'selected' : ''} onClick={() => setSection(item)}>{item}</button>)}</nav>
    {['Providers', 'Provider Products', 'Plan Mappings', 'Coverage'].includes(section) ? <section><div className="section-heading"><h2>{section}</h2><button onClick={() => { void providerReadiness.refetch(); void providerProducts.refetch(); void planMappings.refetch(); void providerCoverage.refetch(); }}>{t.refresh}</button></div><div className="operation-list">{((section === 'Providers' ? providerReadiness.data : section === 'Provider Products' ? providerProducts.data : section === 'Plan Mappings' ? planMappings.data : providerCoverage.data ? [providerCoverage.data] : []) ?? []).map((row, index) => <article key={String(row.id ?? row.providerId ?? index)}><pre>{JSON.stringify(row, null, 2)}</pre></article>)}</div>{providerReadiness.error || providerProducts.error || planMappings.error || providerCoverage.error ? <p role="alert">{t.error}</p> : null}<p>Provider values are simulated or unverified unless explicitly documented. Wholesale cost and margin are shown only when known.</p></section> : section === 'Provider Operations' ? <section><div className="section-heading"><h2>Provider operations</h2><button onClick={() => { void operations.refetch(); void providerSummary.refetch(); void reconciliationIssues.refetch(); void health.refetch(); }}>{t.refresh}</button></div>
      <div className="summary-grid"><article><span className="eyebrow">Provider health</span><h3 className="summary">{providerSummary.data?.provider?.healthStatus ?? 'Unavailable'}</h3><p>{providerSummary.data?.provider?.displayName ?? 'Mock provider'} · simulated</p></article><article><span className="eyebrow">Pending operations</span><h3 className="summary">{providerSummary.data?.pendingOperations ?? 0}</h3></article><article><span className="eyebrow">Failed operations</span><h3 className="summary">{providerSummary.data?.failedOperations ?? 0}</h3></article><article><span className="eyebrow">Review flags</span><h3 className="summary">{providerSummary.data?.openReconciliationIssues ?? 0}</h3></article></div>
      {operations.isPending && <p>{t.loading}</p>}{operations.error && <p role="alert">{t.error}</p>}<div className="operation-list">{operations.data?.map(operation => <article key={operation.id}><div className="section-heading"><strong>{operation.operationType.replaceAll('_', ' ')}</strong><span className={`status ${operation.status === 'SUCCEEDED' ? 'ready' : ''}`}>{operation.status}</span></div><p>{operation.entityType} · {operation.entityId}</p><p>Attempts: {operation.attempts} · {operation.safeErrorCode ?? 'No error recorded'}</p></article>)}{operations.data?.length === 0 && <p>No provider operations recorded.</p>}</div>
      <h2>Review flags</h2>{reconciliationIssues.error && <p role="alert">{t.error}</p>}<div className="operation-list">{reconciliationIssues.data?.map(issue => <article key={issue.id}><strong>{issue.kind.replaceAll('_', ' ')}</strong><p>{issue.entityType} · {issue.entityId}</p><p>{issue.safeDetails}</p></article>)}{reconciliationIssues.data?.length === 0 && <p>No open reconciliation issues.</p>}</div>
    </section> : section === 'Plans' ? <section><div className="section-heading"><h2>{t.plans}</h2><button onClick={() => { void plans.refetch(); void health.refetch(); }}>{t.refresh}</button></div>
      {plans.isPending && <p>{t.loading}</p>}{plans.error && <p role="alert">{t.error}</p>}<div className="plans">{plans.data?.map(plan => <article key={plan.id}><span className="eyebrow">{plan.name}</span><h3>{plan.dataGb}<small> GB</small></h3><p>{plan.durationDays} {t.days}</p><strong>{new Intl.NumberFormat(locale === 'ht' ? 'fr-HT' : locale, { style: 'currency', currency: plan.currency }).format(plan.priceCents / 100)}</strong><div className="pricing">{plan.pricingLabel}</div></article>)}</div>
    </section> : <section><div className="section-heading"><h2>{section}</h2><button onClick={() => { void health.refetch(); }}>{t.refresh}</button></div><p>This development section is read-only. Customer records, payment details, and live carrier actions are not connected.</p>{section === 'Dashboard' && <p>API status: {health.data ? 'ready' : 'unavailable'} · provider data: simulated.</p>}</section>}
    <footer>KONEKTE · DEVELOPMENT FOUNDATION</footer></main>;
}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={queryClient}><App/></QueryClientProvider>);
